/*
 * Sierra College Computer Engineering Club: Sparkfun AVC
 * Common header file for any definitions we might need in each module
 * Includes utility and math functions.
 * Authors: James Smith, Kristoffer Semelka
 *
 * Todo: Implement stubs to finalize port.
 * For each resolved stub, move prototype in common.h from
 * UNIMPLEMENTED PROTOTYPES to PROTOTYPES.
 */
#include "common.h"
#include <math.h>

/* UNIMPLEMENTED FUNCTION STUBS */
/* Time functions, should be replaced by RTI Module calls */

void delay(uint8_t time)
{
	/* Delays some by some integer amount. */
	;
}

void delayMicroseconds(uint8_t ms)
{
	/* Delays by some integer amount of microseconds. */
	;
}
uint32_t millis()
{
	/* Returns time passed in milliseconds.
	 * We should probably use the RTI module instead. */
	return 0;
}

/* serial port functions; should use calls from spi.h */
void print(char* toPrint)
{
	/* Prints a string to serial. See spi.h */
	;
}
void printChar(char c)
{
	/* Prints a single byte/character to serial. */
	;
}
uint8_t available()
{
	/* Returns how many bytes are available in spi buffer, e.g.
	 * radio communication.
	 */
	return 0.f;
}

void readBytes(char* dest, uint8_t n)
{
	/* Reads n bytes into dest buffer. */
	;
}
void printFormat(uint8_t value, format f)
{
	/* Prints value in format f (valid formats are BIN, DEC, and HEX). */
	switch (f)
	{
		case BIN:
			break;

		case DEC:
			break;

		case HEX:
			break;

		default:
			printFormat(value, DEC);
	}
}

char transmitByte(char byte)
{
	/* See: spiTransmitData(...) in spi.h */
	/* Transmits a byte via spi (or sci?) and waits for a byte in response. */
	return (char) 0xFF;
}

#define HIGH 1
#define LOW 0
void digitalWrite(uint8_t val,uint8_t pin)
{
	/* Writes val to pin. */
	;
}
void spiSetBitOrder( uint8_t b)
{
	/* This *might* be autogenerated by Halcogen in spi.h's spiInit() already. */
	;
}
void spiSetDataMode( uint8_t mode)
{
	;
}
void spiSetClockDivider( uint8_t div)
{
	;
}

#define MSBFIRST 0
#define SPI_MODE0 0
#define SPI_CLOCK_DIV4 0
#define INPUT 0x00
#define OUTPUT 0x00

void pinMode(uint8_t pin, uint8_t mode)
{
	/* Sets pin to mode. */
	;
}
#define _BV(val) ( 1<<(val) )

float *parseTo2DArray(char *string)
{	/* To-do.
	 * Parses a two-dimensional array out of a string of values. 
	 */
	return (float*) 0;
}

float *parseToArray(char *string)
{	/* To-do
	 * Parses an array out of a string of values.
	 */
	return (float*) 0;
}

float findAngle(vector vec)
{
	/* Takes a vector, and finds its angle with respect to the positive x-axis. */
	float radians = atan2(-1 * vec.y, vec.x);
	return 180.f * radians / M_PI;
}

float norm (vector point)
{
	/* standard norm of a vector */

	return sqrt(pow(point.x, 2) + pow(point.y, 2));
}

vector diff(vector P1, vector P0)
{
	/* standard vector difference P1 - P0 */
	
	vector difference;
	difference.x = P1.x - P0.x;
	difference.y = P1.y - P0.y;

	return difference;
}

uint8_t max(uint8_t a, uint8_t b)
{
	if( a < b )
	{
		return b;
	}
	else
	{
		return a;
	}
}

uint8_t min(uint8_t a, uint8_t b)
{
	if( a < b )
	{
		return a;
	}
	else
	{
		return b;
	}
}
